### ISSUE TITLE
请问可以设置默认选择项吗？

### ISSUE THREAD

**Issue by jasonbigl** [vue-multiple/select#2]
用了这个感觉挺好用的，但是看文档好像无法设置默认选择项？没发现有setSelected之类的方法

**Comment by savoygu** [comment]
把 v-model 指定为选择项的 value 值，就选中了，比如：
![image](https://user-images.githubusercontent.com/9302866/41388317-f63f22c2-6fbd-11e8-9c61-b43a9b557a82.png)

**Comment by jasonbigl** [comment]
@savoygu 哈哈，是的，谢谢啦，不好意思，忘记v-model了。。。
